#This file is generated by AI, we asked Claude to index our code, and then gave it our testing plan for PM4. 
#We ran these tests to make sure they are all valid tests. 
#As of pre PM5, 7 tests fail, 3 pass. 

import pytest

from cogs import grades as grades_cog
from cogs import professors as professors_cog
from cogs import courses as courses_cog
from utils import charts
from utils import rmp


# -----------------------------
# 1. grades.py calls missing generate_grade_bar
# -----------------------------
@pytest.mark.asyncio
async def test_missing_generate_grade_bar():
    interaction = type("I", (), {})()
    interaction.response = type("R", (), {"defer": lambda *a, **k: None})()
    interaction.followup = type("F", (), {"send": lambda *a, **k: None})()

    cog = grades_cog.GradesCog(bot=None)

    with pytest.raises(AttributeError):
        await cog.grades.callback(cog, interaction, "CS 3114")


# -----------------------------
# 2. grades.py calls missing generate_compare_bar
# -----------------------------
@pytest.mark.asyncio
async def test_missing_generate_compare_bar():
    interaction = type("I", (), {})()
    interaction.response = type("R", (), {"defer": lambda *a, **k: None})()
    interaction.followup = type("F", (), {"send": lambda *a, **k: None})()

    cog = grades_cog.GradesCog(bot=None)

    with pytest.raises(AttributeError):
        await cog.compare.callback(cog, interaction, "CS 2114", "CS 3114")


# -----------------------------
# 3. rmp.py parses wrong GraphQL field
# -----------------------------
@pytest.mark.asyncio
async def test_rmp_wrong_graphql_parsing(monkeypatch):
    class FakeResponse:
        status = 200

        async def json(self, content_type=None):
            return {
                "data": {
                    "search": {
                        "teachers": {
                            "edges": [
                                {"node": {
                                    "firstName": "Test",
                                    "lastName": "Prof",
                                    "numRatings": 10
                                }}
                            ]
                        }
                    }
                }
            }

        async def __aenter__(self): return self
        async def __aexit__(self, *args): return False

    class FakeSession:
        def __init__(self, *args, **kwargs):
            pass

        async def __aenter__(self): return self
        async def __aexit__(self, *args): return False
        def post(self, *args, **kwargs): return FakeResponse()

    monkeypatch.setattr(rmp.aiohttp, "ClientSession", FakeSession)

    prof = await rmp.search_professor("Test Prof")

    assert prof is not None


# -----------------------------
# 4. /professor crashes when None returned
# -----------------------------
@pytest.mark.asyncio
async def test_professor_none_crash(monkeypatch):
    async def fake_search(name):
        return None

    monkeypatch.setattr(professors_cog, "search_professor", fake_search)

    interaction = type("I", (), {})()
    interaction.response = type("R", (), {"defer": lambda *a, **k: None})()
    interaction.followup = type("F", (), {"send": lambda *a, **k: None})()

    cog = professors_cog.ProfessorsCog(bot=None)

    with pytest.raises(Exception):
        await cog.professor.callback(cog, interaction, "Unknown")


# -----------------------------
# 5. autocomplete filter bug (returns empty)
# -----------------------------
def test_autocomplete_filter_bug():
    results = grades_cog.autocomplete_course("CS")
    assert len(results) > 0


# -----------------------------
# 6. chart filename mismatch
# -----------------------------
def test_chart_filename_mismatch():
    fake = {"A": 10, "B": 20, "C": 5, "D": 2, "F": 1}

    file = charts.grade_bar("CS 3114", fake, "Fall")

    assert file.filename == "grade.png"


# -----------------------------
# 7. bar label mismatch ordering bug
# -----------------------------
def test_bar_label_mismatch():
    fake = {"B": 20, "A": 10, "C": 5, "D": 2, "F": 1}

    file = charts.grade_bar("CS 3114", fake, "Fall")

    assert file is not None


# -----------------------------
# 8. course parsing case sensitivity bug
# -----------------------------
def test_course_case_sensitivity_bug():
    raw = "cs 2114 Software Design"

    rows, notes = courses_cog._format_recommendation_payload(raw)

    assert "CS 2114" in rows


# -----------------------------
# 9. recommendation payload parsing bug
# -----------------------------
def test_recommendation_payload_bug():
    raw = """
    CS 3214 Systems
    CS 3704 Software Engineering
    Balance workload
    """.strip()

    rows, notes = courses_cog._format_recommendation_payload(raw)

    assert "CS 3214" in rows
    assert "CS 3704" in rows
    assert "Balance" in notes


# -----------------------------
# 10. recommendation flow integration mismatch
# -----------------------------
def test_recommend_flow_bug():
    choices = {c.value for c in courses_cog.LEVEL_CHOICES}

    assert "junior" in choices